export const SKIP_WAITING = 'sw/SKIP_WAITING';
export const GET_VERSION = 'sw/GET_VERSION';
export const GET_CHANGELOG = 'sw/GET_CHANGELOG';
export const CLIENTS_CLAIM = 'sw/CLIENTS_CLAIM';

export const EXEC_QUEUED_REQUESTS = 'sw/EXEC_QUEUED_REQUESTS';
export const QUEUED_REQUEST_RESPONSE = 'sw/QUEUED_REQUEST_RESPONSE';
