name: Publishing NPM package

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm build
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Notify slack of successful publish
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C7AERGTRC\",\"text\":\":roket: :package: New version (v${{ steps.publish.version }}) of `@panenco/pwa-utils` available!\"}'
        if: steps.publish.type != 'none'
